# Generated by Django 5.1.7 on 2025-03-27 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo_app", "0003_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="prospect",
            name="conversion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prospect",
            name="status",
            field=models.CharField(
                choices=[
                    ("prospect", "Prospect"),
                    ("converted", "Converted Client"),
                    ("inactive", "Inactive"),
                ],
                default="prospect",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClientSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_domain", models.CharField(blank=True, max_length=255)),
                ("domain_verified", models.BooleanField(default=False)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("subscription_active", models.BooleanField(default=True)),
                ("enable_sms_notifications", models.BooleanField(default=False)),
                ("enable_email_notifications", models.BooleanField(default=True)),
                ("enable_online_payments", models.BooleanField(default=False)),
                ("enable_staff_accounts", models.BooleanField(default=False)),
                ("max_staff_accounts", models.IntegerField(default=1)),
                ("twilio_account_sid", models.CharField(blank=True, max_length=255)),
                ("twilio_auth_token", models.CharField(blank=True, max_length=255)),
                ("twilio_phone_number", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prospect",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_settings",
                        to="demo_app.prospect",
                    ),
                ),
            ],
        ),
    ]
